### ISSUE TITLE
Sample packer template? 

### ISSUE THREAD

**Issue by fernflower** [ppc64le-cloud/packer-plugin-powervs#246]
Our team would like to try out the powervs plugin for building some images from cloud base ppc64le rhel ones, but I'm struggling a bit with coming up with the template, specifically the sources definition.

Is there an example with all supported options that I could refer to? Ideally I'm looking for something similar to what ibmcloud vpc packer plugin provides https://github.com/IBM/packer-plugin-ibmcloud?tab=readme-ov-file#packer-template-in-detail

**Comment by mkumatag** [comment]
Some examples written here - https://github.com/ppc64le-cloud/packer-plugin-powervs/tree/main/builder/examples/apache_server but need to enhance it further with more text etc..

**Comment by fernflower** [comment]
Thank you, with the example given paired with source code reading and experimenting I managed to get something working till the hard crash during instance creation step on failed volume list. More details below.

Although the [`account_id`](https://github.com/ppc64le-cloud/packer-plugin-powervs/blob/main/builder/powervs/builder.hcl2spec.go#L25) parameter is not specified as required in the example above, I never got past the obscure early fail `Build 'powervs' errored after 611 milliseconds 39 microseconds: You are not authorized to use this API.` until I set it to the one-section-before-last from the workspace_crn. 

Steps to reproduce:
1. Create the template.
( `rhel-9-6-0-20241209-d-1` is the rhel cloud base image that was uploaded to the ibmcloud beforehand)

```
{
    "variables":
        {
            "apikey": "MY_SECRET_API_KEY",
            "access_key": "MY_SECRET_ACCESS_KEY",
            "secret_key": "MY_SECRET_SECRET_KEY",
            "playbook_file": "",
            "extra_arguments": ""
        },
    "builders":[
        {
            "type": "powervs",
            "account_id": "4207b73c20f249499b08ed2136bb1819",
            "service_instance_id": "3f595cdc-b316-48a6-b6df-d8ac004c6078",
            "api_key": "{{ user `apikey` }}",
            "debug": true,
            "zone": "us-east",
            "source": {
                "name": "rhel-9-6-0-20241209-d-1"
            },
            "instance_name": "packer-build-{{timestamp}}",
            "key_pair_name": "ivasilev",
            "ssh_username": "root",
            "ssh_private_key_file": "~/.ssh/ci_id_rsa",
            "ssh_timeout": "30m",
            "capture": {
                "name": "target-image-1",
                "cos": {
                    "bucket": "tft-image-import",
                    "region": "us-east",
                    "access_key": "{{user `access_key`}}",
                    "secret_key": "{{user `secret_key`}}"
                }
            }
        }
    ],
    "provisioners":[
        {
            "type": "ansible",
            "playbook_file": "{{user `playbook_file`}}",
            "extra_arguments": [ "-vv", "--extra-vars", "{{user `ansible_extra_vars`}}" ],
            "ansible_env_vars": [ "ANSIBLE_LOAD_CALLBACK_PLUGINS=1", "ANSIBLE_STDOUT_CALLBACK=debug" ],
            "use_proxy": false
        }
    ]
}
```
2. Run `packer build -var playbook_file=../images/playbooks/compose/build.yaml ../images/packer/ibmcloud-power-ansible.json`

3. Packer will successfully locate the image and create the network, but will subsequently fail on instance creation during volume list. 

```
ivasilev@ivasilev-thinkpadp1gen4i:~/projects/ansible-baseos-ci/cli$ packer build -var playbook_file=../images/playbooks/compose/build.yaml ../images/packer/ibmcloud-power-ansible.json 
powervs: output will be in this color.

==> powervs: Importing the Base Image
    powervs: Image found with ID: fe2bd832-1dc3-4fb1-81bd-8fd821745392
==> powervs: Creating network
    powervs: Network Created, Name: public-192_168_8_48-28-VLAN_2091, ID: 2a9d0ce7-7bc0-436a-b79e-8748411b1db1
==> powervs: Creating Instance
    powervs: Creating Instance
==> powervs: failed to get instance: failed to Get PVM Instance 1a842322-2ca1-4b0f-b710-bd61a7186f85 :[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}][500] pcloudPvminstancesGetInternalServerError {"description":"unable to get attached volumes for server 1a842322-2ca1-4b0f-b710-bd61a7186f85: unable to get the server volume attachment list: Internal Server Error","error":"internal server error"}
==> powervs: Deleting the Network
    powervs: Successfully deleted network
Build 'powervs' errored after 40 seconds 912 milliseconds: unexpected EOF

==> Wait completed after 40 seconds 912 milliseconds

==> Some builds didn't complete successfully and had errors:
--> powervs: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x140 pc=0x1295cc0]
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: goroutine 24 [running]:
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: github.com/ppc64le-cloud/packer-plugin-powervs/builder/powervs.(*StepCreateInstance).Run(0xc0007da270, {0x1753b12?, 0x491c40?}, {0x1c6ead0, 0xc0007da2a0})
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	github.com/ppc64le-cloud/packer-plugin-powervs/builder/powervs/step_create_instance.go:68 +0x560
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc0007da300, {0x1c6ebe8, 0xc000516050}, {0x1c6ead0, 0xc0007da2a0})
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.5.4/multistep/basic_runner.go:73 +0x29b
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: github.com/ppc64le-cloud/packer-plugin-powervs/builder/powervs.(*Builder).Run(0xc00047ed88, {0x1c6ebe8, 0xc000516050}, {0x1c75420, 0xc0007da060}, {0x1c54420, 0xc000620000})
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	github.com/ppc64le-cloud/packer-plugin-powervs/builder/powervs/builder.go:132 +0x7a4
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc0008ca040, 0x1?, 0xc0004eef10)
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.5.4/rpc/builder.go:120 +0x1d1
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: reflect.Value.call({0xc000b122a0?, 0xc0000ac7a8?, 0x13?}, {0x17470ee, 0x4}, {0xc000401ef8, 0x3, 0x3?})
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	reflect/value.go:596 +0xca6
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: reflect.Value.Call({0xc000b122a0?, 0xc0000ac7a8?, 0x4bd870?}, {0xc0004f6ef8?, 0xc0004ee210?, 0xc?})
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	reflect/value.go:380 +0xb9
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: net/rpc.(*service).call(0xc0008ca080, 0xc0008ca000, 0xc0004ee248, 0xc0004ee250, 0xc0008c0180, 0xc0005129a0, {0x13ec320?, 0xc0004eef0c?, 0x1301be5?}, {0x13aaac0, ...}, ...)
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	net/rpc/server.go:381 +0x20e
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: created by net/rpc.(*Server).ServeCodec in goroutine 1
2024/12/16 13:24:52 packer-plugin-powervs_v0.2.5_x5.0_linux_amd64 plugin: 	net/rpc/server.go:478 +0x3d7
2024/12/16 13:24:52 [INFO] (telemetry) ending powervs
2024/12/16 13:24:52 ui error: Build 'powervs' errored after 40 seconds 912 milliseconds: unexpected EOF
2024/12/16 13:24:52 ui: 
==> Wait completed after 40 seconds 912 milliseconds
2024/12/16 13:24:52 machine readable: error-count []string{"1"}
2024/12/16 13:24:52 ui error: 
==> Some builds didn't complete successfully and had errors:
2024/12/16 13:24:52 /home/ivasilev/.packer.d/plugins/github.com/ppc64le-cloud/powervs/packer-plugin-powervs_v0.2.5_x5.0_linux_amd64: plugin process exited
2024/12/16 13:24:52 machine readable: powervs,error []string{"unexpected EOF"}
2024/12/16 13:24:52 ui error: --> powervs: unexpected EOF
2024/12/16 13:24:52 ui: 
==> Builds finished but no artifacts were created.
2024/12/16 13:24:52 [INFO] (telemetry) Finalizing.
2024/12/16 13:24:52 waiting for all plugin processes to complete...
2024/12/16 13:24:52 /home/ivasilev/.packer.d/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.2_x5.0_linux_amd64: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

This feels like a bug in the plugin (wrong endpoint for volumes retrival -> empty list -> attempt to get a volume id from the list?) as I can manually list created volume for this vm just fine and the machine is also accessible by public ip.

Thanks in advance for any pointers!

**Comment by mkumatag** [comment]
This error thrown while a get call for the instance post creation in the following line
https://github.com/ppc64le-cloud/packer-plugin-powervs/blob/2d0d6fe5139ff5e613ecf00b724ef88db019fb76/builder/powervs/step_create_instance.go#L64

This error is coming all the way from the underneath infrastructure(500 error).

**Comment by mkumatag** [comment]
and then try printing the instance without checking if it is really nil or not!
https://github.com/ppc64le-cloud/packer-plugin-powervs/blob/2d0d6fe5139ff5e613ecf00b724ef88db019fb76/builder/powervs/step_create_instance.go#L68 which can be improved to avoid breaking/segv

**Comment by mkumatag** [comment]
This is because IAM roles required for the api key to fetch the missing account id, hence the failure. Need the documentation for this one as well.
> Although the [`account_id`](https://github.com/ppc64le-cloud/packer-plugin-powervs/blob/main/builder/powervs/builder.hcl2spec.go#L25) parameter is not specified as required in the example above, I never got past the obscure early fail `Build 'powervs' errored after 611 milliseconds 39 microseconds: You are not authorized to use this API.` until I set it to the one-section-before-last of the workspace_crn string.

**Comment by mkumatag** [comment]
Created an issue to track the documentation enhancement - https://github.com/ppc64le-cloud/packer-plugin-powervs/issues/250
